# <center> Hassan Lab 02 practice </center>

In [1]:
import numpy as np
A = np.array(([1,2,3,4,5], [2,3,4,5,6]))
print(f" The 2D array is : \n {A}")
print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is a
print(f"The dimension of an array: {A.shape}")
print(f"The size of an array: {A.size}") 

 The 2D array is : 
 [[1 2 3 4 5]
 [2 3 4 5 6]]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int32
The dimension of an array: (2, 5)
The size of an array: 10


In [18]:
import numpy as np
C = np.array(([1,2,3,4],[5,6,7,8]))
print (f"The is the 2D array {C}")
print (f"Print the type of 2D array {type(C)}")
print (f"Print the dtype of 2D array {C.dtype}")
print (f"Print the size of 2D array {C.size}")
print (f"Print the dtype of 2D array {C.shape}")


The is the 2D array [[1 2 3 4]
 [5 6 7 8]]
Print the type of 2D array <class 'numpy.ndarray'>
Print the dtype of 2D array int32
Print the size of 2D array 8
Print the dtype of 2D array (2, 4)


In [42]:
import numpy as np
r1 = [1,2,3,4]
r2 = [1,2,3,4]
r3 = [1,2,3,4]
r4 = [1,2,3,4]
M  = np.array((r1,r2,r3,r4))
print(f" This is 4x4 matrix {M}")
print(f" The 8x2 matrix: \n {M.reshape(8,2)}")

 This is 4x4 matrix [[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
 The 8x2 matrix: 
 [[1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]]


In [43]:
import numpy as np
B = np.array(([1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]))
print(f"Print the dtype of 2D array /n {B})
print (f"Print the dtype of 2D array {B.dtype}")
print (f"Print the type of 2D array {type(B)}")
print (f"Print the shape of 2D array {B.shape}")


SyntaxError: unterminated string literal (detected at line 3) (2501632543.py, line 3)

In [44]:
import numpy as np
r1 = [1,2,3,4]
r2 = [3,6,3,4]
r3 = [1,2,9,4]
r4 = [1,4,5,4]
A = np.array((r1,r2,r3,r4))
print(f" The 4x4 Matrix is : \n {A}")
print(f" The 8x2 matrix: \n {A.reshape(8,2)}")


 The 4x4 Matrix is : 
 [[1 2 3 4]
 [3 6 3 4]
 [1 2 9 4]
 [1 4 5 4]]
 The 8x2 matrix: 
 [[1 2]
 [3 4]
 [3 6]
 [3 4]
 [1 2]
 [9 4]
 [1 4]
 [5 4]]


In [56]:
import numpy as np
r1 = [1,2,3,4]
r2 = [3,6,3,4]
r3 = [1,2,9,4]
r4 = [1,4,5,4]
A = np.array((r1,r2,r3,r4))
print(f" The 4x4 Matrix is : \n {A}")
print(f" The 8x2 matrix: \n {A.reshape(8,2)}")
print(f" The 1D array from above matrix using ravel: \n{A.ravel()}")


 The 4x4 Matrix is : 
 [[1 2 3 4]
 [3 6 3 4]
 [1 2 9 4]
 [1 4 5 4]]
 The 8x2 matrix: 
 [[1 2]
 [3 4]
 [3 6]
 [3 4]
 [1 2]
 [9 4]
 [1 4]
 [5 4]]
 The 1D array from above matrix using ravel: 
[1 2 3 4 3 6 3 4 1 2 9 4 1 4 5 4]


In [62]:
import numpy as np
d =  np.arange(1,10)
print(d)

[1 2 3 4 5 6 7 8 9]


In [66]:
import numpy as np
A = np.arange(1,100)
print(f" The array is : \n {A}")

 The array is : 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [67]:
import numpy as np
A = np.zeros([5,5])
print(f" The array is : \n {A}")

 The array is : 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [69]:
# Stepsize is 5
import numpy as np
A = np.arange(1,100,5)
print(f" The array is : \n {A}")

 The array is : 
 [ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]


In [84]:
# Ranging of array 
import numpy as np
A = np.linspace(2,5,100)
print(f" The array is : \n {A}")

 The array is : 
 [2.         2.03030303 2.06060606 2.09090909 2.12121212 2.15151515
 2.18181818 2.21212121 2.24242424 2.27272727 2.3030303  2.33333333
 2.36363636 2.39393939 2.42424242 2.45454545 2.48484848 2.51515152
 2.54545455 2.57575758 2.60606061 2.63636364 2.66666667 2.6969697
 2.72727273 2.75757576 2.78787879 2.81818182 2.84848485 2.87878788
 2.90909091 2.93939394 2.96969697 3.         3.03030303 3.06060606
 3.09090909 3.12121212 3.15151515 3.18181818 3.21212121 3.24242424
 3.27272727 3.3030303  3.33333333 3.36363636 3.39393939 3.42424242
 3.45454545 3.48484848 3.51515152 3.54545455 3.57575758 3.60606061
 3.63636364 3.66666667 3.6969697  3.72727273 3.75757576 3.78787879
 3.81818182 3.84848485 3.87878788 3.90909091 3.93939394 3.96969697
 4.         4.03030303 4.06060606 4.09090909 4.12121212 4.15151515
 4.18181818 4.21212121 4.24242424 4.27272727 4.3030303  4.33333333
 4.36363636 4.39393939 4.42424242 4.45454545 4.48484848 4.51515152
 4.54545455 4.57575758 4.60606061 4.63636364 

In [89]:
import numpy as np
A = np.identity(5)
print(f" The array is : \n {A}")


 The array is : 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [90]:
import numpy as np
r1 = [1,2,3,4]
r2 = [3,6,3,4]
r3 = [1,2,9,4]
r4 = [1,4,5,4]
A = np.array((r1,r2,r3,r4))
print(f" The Matrix is : \n {A}")
print(f" The row wise sum is : {A.sum(axis=1)}")
print(f" The column wise sum is : {A.sum(axis=0)}")

 The Matrix is : 
 [[1 2 3 4]
 [3 6 3 4]
 [1 2 9 4]
 [1 4 5 4]]
 The row wise sum is : [10 16 16 14]
 The column wise sum is : [ 6 14 20 16]


In [92]:
import numpy as np
r1 = [1,2,3,4]
r2 = [3,6,3,4]
r3 = [1,2,9,4]
r4 = [1,4,5,4]
A = np.array((r1,r2,r3,r4))
print(f" The Matrix is : \n {A}")
print(f" The row wise sum is : {A.sum(axis=1)}")
print(f" The column wise sum is : {A.sum(axis=0)}")

 The Matrix is : 
 [[1 2 3 4]
 [3 6 3 4]
 [1 2 9 4]
 [1 4 5 4]]
 The row wise sum is : [10 16 16 14]
 The column wise sum is : [ 6 14 20 16]


In [93]:
import numpy as np
r1 = [1,2,3,4]
r2 = [3,6,3,4]
r3 = [1,2,9,4]
r4 = [1,4,5,4]
A = np.array((r1,r2,r3,r4))
print(f" The Matrix is : \n {A}")
print(f" The transpose is : \n {A.T}")

 The Matrix is : 
 [[1 2 3 4]
 [3 6 3 4]
 [1 2 9 4]
 [1 4 5 4]]
 The transpose is : 
 [[1 3 1 1]
 [2 6 2 4]
 [3 3 9 5]
 [4 4 4 4]]


In [94]:
import numpy as np
r1 = [1,2,3,4]
r2 = [3,6,3,4]
r3 = [1,2,9,4]
r4 = [1,4,5,4]
A = np.array((r1,r2,r3,r4))
print(f" The 4x4 Matrix is : \n {A}")
print(f" The 8x2 matrix: \n {A.reshape(8,2)}")


 The 4x4 Matrix is : 
 [[1 2 3 4]
 [3 6 3 4]
 [1 2 9 4]
 [1 4 5 4]]
 The 8x2 matrix: 
 [[1 2]
 [3 4]
 [3 6]
 [3 4]
 [1 2]
 [9 4]
 [1 4]
 [5 4]]


In [95]:
import numpy as np
r1 = [1,2,3,4]
r2 = [3,6,3,4]
r3 = [1,2,9,4]
r4 = [1,4,5,4]
A = np.array((r1,r2,r3,r4))
print(f" The 4x4 Matrix is : \n {A}")
print(f" The 1D array from above matrix using ravel: \n {A.ravel()}")


 The 4x4 Matrix is : 
 [[1 2 3 4]
 [3 6 3 4]
 [1 2 9 4]
 [1 4 5 4]]
 The 1D array from above matrix using ravel: 
 [1 2 3 4 3 6 3 4 1 2 9 4 1 4 5 4]


In [99]:
import numpy as np
a = [1, 160, 31, 400]
A = np.array(a)
print(f"The original array: {A}")
print(f"The index of maximum value in array is: {A.argmax()}")
print(f"The index of minimum value in array is: {A.argmin()}")
print(f"Sorted Indexes: {A.argsort()}")

The original array: [  1 160  31 400]
The index of maximum value in array is: 3
The index of minimum value in array is: 0
Sorted Indexes: [0 2 1 3]


In [102]:
import numpy as np
f1=np.full((2,2),2)
f1



array([[2, 2],
       [2, 2]])

In [103]:
import numpy as np
f2=np.full((2,2),5)
f2



array([[5, 5],
       [5, 5]])

In [104]:
a = np.vstack([f1, f2])
a



array([[2, 2],
       [2, 2],
       [5, 5],
       [5, 5]])

In [105]:
b = np.hstack([f1, f2])
b


array([[2, 2, 5, 5],
       [2, 2, 5, 5]])

In [106]:
a = np.column_stack([f1, f2])
a

array([[2, 2, 5, 5],
       [2, 2, 5, 5]])

In [107]:
import numpy as np
a = np.full((2,3), 5)
a


array([[5, 5, 5],
       [5, 5, 5]])

In [108]:
np.save("untitled.npy", a)

In [109]:
savedMatrix = np.load('untitled.npy')
savedMatrix

array([[5, 5, 5],
       [5, 5, 5]])

In [111]:
import numpy as np
f1=np.full((2,2),5)
print("\nf1 = \n",f1)
f2=np.full((2,2), 3)
print("\nf2 = \n", f2)
print("point to point multiplication = ",f1*f2)
print("point to point multiplication = ", np.dot(f1,f2))


f1 = 
 [[5 5]
 [5 5]]

f2 = 
 [[3 3]
 [3 3]]
point to point multiplication =  [[15 15]
 [15 15]]
point to point multiplication =  [[30 30]
 [30 30]]


# 02. Pandas
### Example 01
- Create a Dictionary and convert them into data frames also check its datatype

In [114]:
StuDict={"Name": ["Aqsa","Esha", "Ayesha", "Ayra", "Arfa", "Afsa", "Abdul", "Saadia","ID": ["SID-1","SID-2", "SID-3", "SID-4", "SID-5","SID-6", "SID-7", "SID-8", "SID-9"],
"Rol1_no": [1,2,3,4,5,6,7,8,9,10],
"Semester" : [7,7,7,7,6,6,6,5,8,8]}
StuDict

SyntaxError: closing parenthesis '}' does not match opening parenthesis '[' on line 1 (2890721477.py, line 3)